### PR TITLE
RD-5894 Update authorization.conf

### PR DESCRIPTION
**Pull request by qooban**
As Deployment Wizard Buttons was removed (https://github.com/cloudify-cosmo/cloudify-stage/pull/2167) no need to keep unused permissions in `authorization.conf`.

### CODE REVIEW

**Review by Vorbert-Kruk — APPROVED** [review]
Looks good 💪

**Comment by tehasdf** [comment]
ah this won't work until after #1397, sorry. Give us some time :)

**Comment by qooban** [comment]
> ah this won't work until after #1397, sorry. Give us some time :)

OK, no issues :-)
I've just subscribed to https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1397, so we'll update this PR once it's merged.

**Comment by qooban** [comment]
@tehasdf Is the CI failure related to issues in Jenkins or that's something else?
Seeing that it was possible to merge https://github.com/cloudify-cosmo/cloudify-manager-install/pull/1407 I suspect something else 🤔

**Comment by qooban** [comment]
@geokala Once you got the fix for CI pipeline in this repo, please either let me know or just trigger CI here and merge it 🙂 No hurry.

**Comment by geokala** [comment]
@qooban A bunch of failures are down to the rest client part of this being merged (but tested in the manager part, so... yeah, I broke eeeeverything <headdesk>): https://github.com/cloudify-cosmo/cloudify-manager/pull/3826
I'll check through other open issues once the fires are out.

**Comment by qooban** [comment]
@tehasdf Thanks for merging this PR. Closing RD-5894.

**Pull request merged**
